# Generated by Django 5.1.4 on 2025-01-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='long',
        ),
    ]
