# Generated by Django 5.1.4 on 2025-01-08 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batasdesa', '0001_initial'),
        ('peta', '0002_remove_superhero_lat_remove_superhero_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunanpogung',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peta.superhero'),
        ),
    ]
